# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock-2.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0,1
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# GENERAL

shape {
    monitor =
    size = 600, 700
    color = rgba(69, 64, 61, 0.33)
    rounding = 50 
    border_size = 4
    border_color = rgba(0, 0, 0, 0)
    position = 0,-150
    halign = center
    valign = center
}


# # NAME
# label {
#     monitor =
#     text = 
#     color = rgb(212, 190, 152)
#     font_size = 20
#     font_family = SF Pro Display Bold
#     position = 0, 500
#     halign = center
#     valign = center
# }

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(212, 190, 152, 0.90)
    font_size = 144
    font_family = SF Pro Display Bold
    position = 0, 400
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(168, 153, 132, 0.90)
    font_size = 22
    font_family = SF Pro Display Bold
    position = 0, 270
    halign = center
    valign = center
}


# Profie-Photo
image {
    monitor =
    path = ~/.config/hypr/profile.png
    border_size = 2
    border_color = rgba(216, 166, 87, 0.85)
    size = 200
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, -50
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgba(69, 64, 61, 0.45)
    rounding = -1
    border_size = 1
    border_color = rgba(168, 153, 132, 0.80)
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 0, -200
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgb(212, 190, 152)
    font_size = 16
    font_family = SF Pro Display Bold
    position = 0, -200
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(29, 32, 33, 0)
    inner_color = rgba(40, 40, 40, 0.78)
    font_color = rgb(212, 190, 152)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = Enter password
    hide_input = false
    position = 0, -270
    halign = center
    valign = center
}

# Information
label {
    monitor =
    text = cmd[update:2500] echo -e "$(~/.config/hypr/scripts/hyprlock-battery.sh)"
    color = rgb(212, 190, 152)
    font_size = 20
    font_family = SF Pro Display Bold  
    halign = center
    valign = bottom
}