-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Iiyama North America PL2792Q 1152171401565",
  mode = "2560x1440@59.95",
  position = "1440x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Display 0x06B1 0x001824A1",
  mode = "2880x1920@60.00",
  position = "1946x1440",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Philips Consumer Electronics Company PHL 242B1 UK02140041541",
  mode = "1920x1080@60.00",
  position = "360x0",
  scale = 1,
  transform = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Display 0x06B1 0x001824A1", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Display 0x06B1 0x001824A1" })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Display 0x06B1 0x001824A1" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Iiyama North America PL2792Q 1152171401565", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Iiyama North America PL2792Q 1152171401565" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Iiyama North America PL2792Q 1152171401565" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Philips Consumer Electronics Company PHL 242B1 UK02140041541", default = true, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:Philips Consumer Electronics Company PHL 242B1 UK02140041541" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Philips Consumer Electronics Company PHL 242B1 UK02140041541" })
