general {
    # Prevent multiple instances of hyprlock starting
    lock_cmd =  ~/.config/hypridle/scripts/hypridle-lock.sh

   

    # Lock our device before sleep
    before_sleep_cmd = ~/.config/hypridle/scripts/hypridle-before-sleep.sh

    # avoid having to press a key twice to turn on the display.
    after_sleep_cmd = ~/.config/hypridle/scripts/hypridle-after-sleep.sh


    # 0 disables sleep inhibition.
    # 1 makes the system wait until hypridle launched general:before_sleep_cmd.
    # 2 (auto) selects either 3 or 1 depending on whether hypridle detects if you want to launch hyprlock before sleep.
    # 3 makes your system wait until the session gets locked by a lock screen app. 
    #   This works with all wayland session-lock apps.
    inhibit_sleep = 2

}



# AFK 1: lock device after 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session \
                 && ~/.config/mqtt/send-mqtt-message.sh "hyprstation-01/session_state" "Locked"
    on-resume = ~/.config/mqtt/send-mqtt-message.sh "hyprstation-01/session_state" "Unlocked"
}

# AFK 2: handles display and RGB power after 15 minutes
listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' \
                 && openrgb --profile ~/.config/OpenRGB/HyprStation-01-LightsOut.orp \
                 && ~/.config/mqtt/send-mqtt-message.sh "hyprstation-01/session_state" "Idle"

    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' \
                && brightnessctl -r \
                && openrgb --profile ~/.config/OpenRGB/HyprStation-01.orp
}

# AFK 3: sleep after 45 minutes (conditional based on power plan)
listener {
    timeout = 2700
    on-timeout = ~/.config/mqtt/send-mqtt-message.sh "hyprstation-01/session_state" "Sleep" \
                 && ~/.config/hypridle/scripts/hypridle-sleep.sh

    on-resume = ~/.config/mqtt/send-mqtt-message.sh "hyprstation-01/session_state" "Online"
}
