general {
    # Prevent multiple instances of hyprlock starting
    lock_cmd = pidof hyprlock || hyprlock

    # Lock our device before sleep
    before_sleep_cmd = loginctl lock-session

    # avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'


    # 0 disables sleep inhibition.
    # 1 makes the system wait until hypridle launched general:before_sleep_cmd.
    # 2 (auto) selects either 3 or 1 depending on whether hypridle detects if you want to launch hyprlock before sleep.
    # 3 makes your system wait until the session gets locked by a lock screen app. 
    #   This works with all wayland session-lock apps.
    inhibit_sleep = 2
}

# Lock after 15 minutes
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# Turn displays off after 20 minutes
listener {
    timeout = 1200

    # screen off when timeout has passed
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'

    # screen on when activity is detected after timeout has fired.
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Optional: stop RGB after 20 minutes
listener {
    #timeout = 1200
    #on-timeout = openrgb --profile ~/.config/OpenRGB/Off.orp
    #on-resume = openrgb --profile ~/.config/OpenRGB/HyprStation-01.orp
}