-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:LG Electronics LG ULTRAWIDE 0x0008092B",
  mode = "3440x1440@59.973",
  position = "0x0",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Hewlett Packard HP V241a 3CQ3400X36",
  mode = "1920x1080@60",
  position = "3440x-190",
  scale = 1,
  transform = 3,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
